root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"   # Output binary location
  cmd = "go build -o ./tmp/main ./cmd/web"   # Corrected path to the main.go
  delay = 1000          # Delay for file changes (ms)
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false   # Ensure that files always trigger reload
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true  # Polling for file changes; set true if file system events are unreliable
  poll_interval = 1000  # Poll interval in ms (optional)
  post_cmd = []
  pre_cmd = []
  rerun = false  # Enable automatic rerun when files change
  rerun_delay = 300  # Delay for rerun after changes (ms)
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
